trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  imageTag: '$(Build.BuildId)'
  acrLoginServer: 'modrekregistry.azurecr.io'
  imageRepo: 'pipeline_dev_home'
  aksNamespace: 'uae-modrek-stock-v2-namespace'
  aksServiceConnection: 'Pipeline-Dev_AKS-Conn'

steps:
- task: Docker@2
  displayName: Home
  inputs:
    containerRegistry: 'Pipeline-Dev_RegConn'
    repository: '$(imageRepo)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageTag)
      latest

- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    connectionType: kubernetesServiceConnection
    kubernetesServiceConnection: '$(aksServiceConnection)'
    namespace: '$(aksNamespace)'
    manifests: |
      k8s/deployment.yaml
      k8s/service.yaml
    containers: |
      $(acrLoginServer)/$(imageRepo):$(imageTag)
